### ISSUE TITLE
Rpcmarshal.marshal never creates Rpc.Int32

### ISSUE THREAD

**Issue by KKostya** [mirage/ocaml-rpc#128]
There is a facility for encoding 32-bit integers into XMLRPC `<i4>` tag:
https://github.com/mirage/ocaml-rpc/blob/master/src/lib/xmlrpc.ml#L44
But this code is unreachable since `Rpcmarshal.marshal` still creates `Int` value instead of `Int32`:
```
# Rpcmarshal.marshal Rpc.Types.( Basic Int32 ) 42l ;;
- : Rpc.t = Rpc.Int 42L
```
While I'd expect `Rpc.Int32 42l` as a result. This conversion is forced here:
https://github.com/mirage/ocaml-rpc/blob/master/src/lib/rpc.ml#L152
And it looks like `Rpcmarshal.marshal` never creates `Int32` values at all.

This is an issue, say, for connecting ocaml-rpc to an existing pyhton XMLRPC code. The python library   reads  `<value>1</value>` as a string `'1'` value --  to get an integer value in python, one needs to encode it as  `<value><i4>1</i4></value>`.

**Comment by mseri** [comment]
If you look at xmlrpc standsrd, all the ints have to be int32, so the issue is actually cmlrpc not using he int tag here: 
https://github.com/mirage/ocaml-rpc/blob/e8765cd5b5aa1d8ee8ce2b274d5f503550ca832d/src/lib/xmlrpc.ml#L41
