### ISSUE TITLE
No support for JSON-RPC notifications

### ISSUE THREAD

**Issue by vycastor** [mirage/ocaml-rpc#142]
In the current ocaml-rpc implementation, since it's designed to be protocol-agnostic, there is no support for JSON-RPC notifications (requests without responses). I think this ought to be fixed, if possible. I already devised a ~working implementation at https://github.com/vycastor/ocaml-rpc but would like to discuss if it's ok for you to try to implement it this way. I didn't create a PR since I wanted to discuss the design first.

It's not very pretty, but at least it doesn't make major changes to the implementation and the types, that was what I intended to avoid, and it provides notification support for any protocol you'd like to use.

**Comment by mseri** [comment]
Looks like an acceptable solution to me tbh

**Comment by vycastor** [comment]
Great! I opened PR [https://github.com/mirage/ocaml-rpc/pull/143](https://github.com/mirage/ocaml-rpc/pull/143).
