### ISSUE TITLE
The metapackage rpc is outdated on Opam

### ISSUE THREAD

**Issue by vycastor** [mirage/ocaml-rpc#150]
It causes dependency problems.

**Comment by mseri** [comment]
I cannot make a release right now. Would you mind sending a PR to the `opam-repository` for `rpc.5.9.0, rpc.6.0.0, rpc.6.1.0, rpc.7.0.0`, requiring `{= version}` of the `rpclib*` and `ppx_deriving_rpc` packages?

**Comment by vycastor** [comment]
Sorry for the (very) late answer. I will do it soon!

**Comment by mseri** [comment]
Thanks!

**Comment by psafont** [comment]
I think this should be closed :)

**Comment by mseri** [comment]
Indeed. Thanks!
