### ISSUE TITLE
Support OCaml 4.10 for ppx_deriving_rpc

### ISSUE THREAD

**Issue by anton-trunov** [mirage/ocaml-rpc#156]
Looks like to support OCaml 4.10 the ppxlib dependency is needed to be updated to >= 0.12.0.

**Comment by mseri** [comment]
Last time I checked it looked a nontrivial change to deal with the doc strings. I made a very brief attempt but got stuck on a type that had become abstract in the meanwhile. @jonludlam do you know how hard it is to update it?
