### ISSUE TITLE
Custom type and ppx_deriving_rpc

### ISSUE THREAD

**Issue by CGenie** [mirage/ocaml-rpc#157]
Hello,

I need to create a custom type, serializable via the `[@@deriving rpcty]` construct.
Basically, it's datetime with custom formatting. I see compiler informing that it can't find `MyModule.typ_of` so I added

```ocaml
let typ_of = Rpc.Types.Basic Rpc.Types.String
```

but then I get

```
Error: This expression has type MyModule.t
       but an expression was expected of type string
```

Anyone have an idea how to do this? I basically want to serialize to string and deserialize to `Core_kernel.Time_ns.t`.

Eq. with Yojson I just added `to_yojson`/`of_yojson` and the ppx can derive it's stuff, here I don't know how :)

**Comment by mseri** [comment]
You should be able to do that using the `Rpc.Abstract` trype.

**Comment by mseri** [comment]
Were you able to solve your issue using the abstract type?

**Comment by CGenie** [comment]
I haven't tried yet, I'll be working on the project on Monday, will let you know :)

**Comment by CGenie** [comment]
OK this helps indeed, thank you!

**Comment by mseri** [comment]
Closing this, feel free to reopen it if needed
