### ISSUE TITLE
Bug when serializing Dict structure

### ISSUE THREAD

**Issue by CGenie** [mirage/ocaml-rpc#158]
Hello,

I have this code:

```ocaml
type t = {
  a: string;
  b: int64;
}

let d = { a = "a"; b = 1L }

let () =
  let rpc = Rpc.Dict [ ("a", Rpc.String d.a);
                     ("b", Rpc.Int d.b) ] in
  Printf.printf "%s\n" (Xmlrpc.to_string rpc)
```

After running I get:

```xml
<value><struct><member><name>a</name><value>a</value></member><member><name>b</name><value>1</value></member></struct></value>
```

The XMLRpc server I'm working with complains that `1` is a string value not an int. In fact [wikipedia](https://en.wikipedia.org/wiki/XML-RPC) explicitly states this example:

```xml
<struct>
  <member>
    <name>foo</name>
    <value><i4>1</i4></value>
  </member>
  <member>
    <name>bar</name>
    <value><i4>2</i4></value>
  </member>
</struct>
```
i.e. `<value>` has the type of element wrapped inside. Or maybe I'm creating the `rpc` structure in a wrong way?

**Comment by CGenie** [comment]
My guess is:
https://github.com/mirage/ocaml-rpc/blob/master/src/lib/xmlrpc.ml#L39-L46
that `Int` type should be converted to `<value><int>`. Similarly `Int32` is converted to `<value><i4>`. Anyways, this is for sure mixed up with the String type, please consult the wikipedia page for the string example (i.e. can be wrapped in `<string>` but need not be).

**Comment by mseri** [comment]
Thanks, indeed, this seems to be related to https://github.com/mirage/ocaml-rpc/issues/128
This PR should fix the issue: https://github.com/mirage/ocaml-rpc/pull/132
Before it is merged it needs to be updated to allow to keep the old behavior, I'll see if I can find some time to update it.

**Comment by mseri** [comment]
@CGenie can you see if using the current PR does solve your issue for `~strict:true`?
It produces:
```xml
<value><struct><member><name>a</name><value>a</value></member><member><name>b</name><value><i8>1</i8></value></member></struct></value>
```

**Comment by CGenie** [comment]
Indeed, this fixes my problems with the XMLRpc server, thank you!

**Comment by mseri** [comment]
Thanks for checking
