### ISSUE TITLE
Method calls with no arguments

### ISSUE THREAD

**Issue by tbrk** [mirage/ocaml-rpc#169]
I'm [trying](https://github.com/tbrk/neos-server-ocaml-client) to interface to the [NEOS servers](https://neos-server.org/neos/xml-rpc.html) using the `Idl` functors. Many of the NEOS methods do not take any arguments. Consider, for example,
```
module NeosInterface(R : Idl.RPC) = struct
  open R
  let unit_p = Idl.Param.mk Rpc.Types.unit

  let ping = R.declare "ping" [] (unit_p @-> returning string_p Idl.DefaultError.err)
end
```

This generates the method xml (`call.xml`):
```
<?xml version="1.0"?>
<methodCall>
    <methodName>ping</methodName>
    <params>
        <param><value><nil/></value></param>
    </params>
</methodCall>
```
which can be sent directly to the server using:
```
curl -v -H "content-type: text/xml" https://neos-server.org:3333 --data @call.xml
```
The server replies:
```
<class 'TypeError'>:ping() takes 1 positional argument but 2 were given
```

However, sending either of the following two strings solicits the correct response.
```
<?xml version="1.0"?>
<methodCall>
    <methodName>ping</methodName>
    <params>
        <param></param>
    </params>
</methodCall>

<?xml version="1.0"?>
<methodCall>
    <methodName>ping</methodName>
    <params></params>
</methodCall>
```

Is there a way to construct this call using `Idl` (from my understanding of the implementation, there is not)? Should there be?

Maybe something like a new value in `Idl.RPC`?
```
val void_returning : 'a Param.t -> 'b Error.t -> (unit -> ('a, 'b) comp fn) fn
```

**Comment by tbrk** [comment]
I've implemented a simple prototype in #170. It's my first time using this library, so maybe my proposition is no good! Don't hesitate to say so.

**Comment by mseri** [comment]
Thanks! It is quite some time that I don't touch this library, it will take some time to remember the internals

**Comment by tbrk** [comment]
I wonder if `void` is a poor choice of keyword. Maybe `noargs` or something else would be better?
```
let ping = R.declare "ping" [] (noargs (returning string_p Idl.DefaultError.err))
```
What do you think? I could easily update #170.

**Comment by mseri** [comment]
I have looked at the code and the example. I wanted to see if we could have a simpler/non breaking implementation, but this looks simple enough.

I agree with you that `noargs` is clearer

**Comment by mseri** [comment]
Thanks a lot for looking into it. If you update the Pr with noargs, I am going to merge it and draft a new release

**Comment by tbrk** [comment]
Thanks @mseri. I've renamed `void` to `noargs`.
