### ISSUE TITLE
Failure to parse XML

### ISSUE THREAD

**Issue by akshayramani** [mirage/ocaml-rpc#22]
The XML parsing seems to fail for an xml of type : 

```
<member><name>VCPUs_params</name><value><struct><member><name/><value><string/></value></member></struct></value></member>
```

This fails with the error
Exception: Xmlrpc.Parse_error ("open_tag(value)", "close_tag(name)", _).

The following XML is parsed successfully

```
<member><name>VCPUs_params</name><value><struct><member><name>Foo</name><value><string/></value></member></struct></value></member>
```

The difference being a non-empty value for the `<name>` tag.

**Comment by gaborigloi** [comment]
@mseri This is not a bug provided empty struct member names are invalid in XML-RPC, so IMO we could close this, but feel free to re-open if this is not the case.
