### ISSUE TITLE
Document the IDL generator

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-rpc#29]
@jonludlam would it be possible to document/add examples of the IDL generator? I maybe plan to use that feature in on one of my project but I'm not sure how to do it properly :p

**Comment by gaborigloi** [comment]
There is some helpful example code in the `example` folder in [`example3_idl.ml`](https://github.com/mirage/ocaml-rpc/blob/master/example/example3_idl.ml)

**Comment by mseri** [comment]
I think we should document the generator and the whole library if we wanto to attract more users and feel less pain when using it. Having to go and look at tests or examples is not a good solution in my opinion
