### ISSUE TITLE
Build failure with OPAM 2

### ISSUE THREAD

**Issue by mato** [mirage/ocaml-rpc#67]
This seems OPAM 2 related, but may be general packaging error. When installing rpc 2.0.0 I get

```
#=== ERROR while compiling rpc.2.0.0 ==========================================#
"": command not found.
```

The error goes away if I create a local pin of the 2.0.0 package and remove `[configure]` from the `build:` section in `opam`.

**Comment by mseri** [comment]
Thanks, I am going to update the opam file and make a PR to the main opam repository

**Comment by gaborigloi** [comment]
I've managed to install rpc.2.2.0 with opam 2 :)
